config/routes.rb
Rails.application.routes.draw do
  root 'courses#index'
  get 'about', to: 'pages#about'
  resources :courses, except: [:index]
  resources :students
  get 'signup', to: 'students#new'
  get 'login', to: 'logins#new'
  post 'login', to: 'logins#create'
  delete 'logout', to: 'logins#destroy'
  post 'course_enroll', to: 'student_courses#create'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
    validates :short_name, presence: true, length: { minimun: 5, maximum: 15 }
    validates :name, presence: true, length: { minimun: 10, maximum: 50 }
    validates :description, presence: true, length: { minimun: 20, maximum: 400 }
    has_many :student_courses
    has_many :students, through: :student_courses
end

app/models/student.rb
class Student < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { minimum: 3, maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i          
    validates :email, presence: true, length: { minimum: 5, maximum: 105 }, uniqueness: { case_sensitive: false },
               format: {with: VALID_EMAIL_REGEX}
    has_secure_password
    has_many :student_courses
    has_many :courses, through: :student_courses
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
   belongs_to :student
   belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :require_user
    helper_method :current_user, :logged_in?
    
    def current_user
       @current_user ||= Student.find(session[:student_id]) if session[:student_id]
    end
   
    def logged_in?
      !!current_user  
    end
    
    def require_user
       if !logged_in?
         flash[:notice] = "You must be logged in to perform this action"
         redirect_to login_path
       end
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :require_admin, only: [:new, :create, :destroy, :update, :edit]
  skip_before_action :require_user
  
    def index
      @courses = Course.all
    end
    
    def new
      @course = Course.new(params[:id])
    end
    
    def show
      @course = Course.find(params[:id])
    end
  
    def edit
     @course = Course.find(params[:id])
    end
    
    def create
    @course = Course.new(course_params)
    if @course.save
     flash[:notice] = "You have successfully created a course!"
     redirect_to @course
    else
      render 'new'
    end
    end
  
  def update
     @course = Course.find(params[:id])
    if @course.update(course_params)
      flash[:notice] = "You have successfully updated your course"
     redirect_to @course
    else
      render 'edit'
    end
  end
  
  def destroy
     @course = Course.find(params[:id])
     @course.destroy
     flash[:danger] = "Your course have successfully deleted"
     redirect_to root_path
  end
  
  private
  
  def set_params
    @course = Course.find(params[:id]) 
  end
  
  def course_params
    params.require(:course).permit(:short_name, :name, :description )
  end
 
  def require_admin
    if logged_in? and !current_user.admin?
    flash[:danger] = "Only admin can perform that action"
    redirect_to root_path
    end
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
   
   skip_before_action :require_user, only: [:new, :create]
    
   def new
       
   end
   
   def create
     student = Student.find_by(email: params[:logins][:email].downcase)
     if student && student.authenticate(params[:logins][:password])
        session[:student_id] = student.id
        flash[:notice] = 'You have successfully login'
        redirect_to student
     else
        flash.now[:notice] = "Something was wrong with your login information"
        render 'new'
     end
   end
   
   def destroy
      session[:student_id] = nil
      flash[:notice] = 'You have successfully log out'
      redirect_to root_path
   end
   
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
skip_before_action :require_user

def about
    
end

end

app/controllers/student_courses_controller.rb
class StudentCoursesController < ApplicationController
   
   def create
      course_to_add = Course.find(params[:course_id])
      unless current_user.courses.include?(course_to_add)
      StudentCourse.create(course: course_to_add, student: current_user)
      flash[:notice] = "You have successfully enrolled in #{course_to_add.name}"
      redirect_to current_user
   else
      flash[:notice] = 'Something was wrong with your enrollment'
      redirect_to root_path
      end
   end
    
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  skip_before_action :require_user, only: [:new, :create]
  before_action :set_params, only: [:update, :show, :edit]
  before_action :require_same_student, only: [:edit, :update]
  
  def index
      @students = Student.all
  end
  
  def show
   
  end
  
  def edit
   
  end
  
  def new
    @student = Student.new
  end
  
  def create
    @student = Student.new(student_params)
    if @student.save
     flash[:notice] = "You have successfully signed up"
     redirect_to @student
    else
      render 'new'
    end
  end
  
  def update
    if @student.update(student_params)
      flash[:notice] = "You have successfully updated your profile"
     redirect_to @student
    else
      render 'edit'
    end
  end
  
  private
  
  def set_params
    @student = Student.find(params[:id]) 
  end
  
  def student_params
    params.require(:student).permit(:name, :email, :password, :password_confirmation)
  end
  
  def require_same_student
    if current_user != @student
      flash[:notice] = "You can only edit or update your own profile"
      redirect_to student_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
 def session_link
   if logged_in? 
    link_to 'Logout', logout_path, method: :delete
   else 
    link_to 'Log in', login_path
   end
  end
end

app/views/courses/_form.html.erb
<div class="container">
    <div class="row sign-up-form">
        <div class="col m12">
            <div class="card-panel">
              <div class="card-title">
               <h3 class="teal-text center"><%= @course.new_record? ? 'Create New Course!' : 'Edit your profile!' %></h3>  
              </div>
               <div class="row">
                <%= form_for(@course, html: { class: 'col m12' }) do | f | %>
                 <div class="row">
                     <div class="input-field col m12">
                        <%= f.text_field :short_name, placeholder: 'Course short name', autofocus: true %>
                        <%= f.label :short_name, class: "active" %>
                     </div>
                 </div>
                    <div class="row">
                     <div class="input-field col m12">
                        <%= f.text_field :name, placeholder: 'Course name', autofocus: true %>
                        <%= f.label :name, class: "active" %>
                     </div>
                 </div>
                 <div class="row">
                     <div class="input-field col m12">
                        <%= f.text_area :description, id: "textarea1", class: "materialize-textarea", 
                                               placeholder: 'Course description', autofocus: true %>
                        <%= f.label :description, class: "active" %>
                     </div>
                 </div>
                  <div class="row">
                    <div class="input-field col m12">               
                     <%= f.button(@course.new_record? ? '<i class="material-icons right">send</i>create course'.html_safe : 
                                     '<i class="material-icons right">send</i>submit changes'.html_safe, 
                                     class: "btn waves-effect waves-light right white-text") %>
                   </div>  
                 </div>
                <% end %>
            </div>  
          </div>
        </div>
    </div>
</div>

app/views/courses/edit.html.erb
<%= render 'form' %>

app/views/courses/index.html.erb
<div class="row">
  <div class="col m12">
   <div class="course_heading">
        <h1>Course listing</h1>
   </div>
  </div>
 </div>
<div class="row">
    <% @courses.each do |course| %>
    <div class="col s12 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= course.short_name %>: <%= truncate(course.name, length: 50) %></span>
          <p><%= truncate(course.description, length: 150) %> </p>
        </div>
        <div class="card-action">
          <% if logged_in? && !(current_user.courses.include?(course)) %>
          <%= link_to "Enroll", course_enroll_path(course_id: course.id), method: :post %>
          <% end %>
          <%= link_to 'Info', course_path(course) %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
               

app/views/courses/new.html.erb
<%= render 'form' %>

app/views/courses/show.html.erb
<div class="row">
    <div class="col s12 m12 l12">
      <div class="show-course">
          <h3 class="course-title"><%= @course.short_name %> : <%= @course.name %></h3>
          <p><%= @course.description %> </p>
        </div>
      
      <div class="course-action">
        <%= link_to 'All courses', root_path, class:"waves-effect waves-light btn amber darken-4" %>
        <% if logged_in? && current_user.admin? %>
        <%= link_to 'Edit courses', edit_course_path(@course), class:"waves-effect waves-light btn amber" %>
        <%= link_to 'Delete', course_path(@course), method: :delete, 
               data: { confirm: 'Are you sure?' }, class:"waves-effect waves-light btn red darken-2" %>
        <% end %>
      </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Tech University</h5>
          <p class="grey-text text-lighten-4">New trainning courses are available in our site </p>
        </div>
        <div class="col l4 offset-l2 s12">
          <h5 class="white-text">Information</h5>
          <ul>
            <li><a class="grey-text text-lighten-3" href="#!">Help</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">About</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Contact Us</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Courses</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      © 2018 Tech University
      <a class="grey-text text-lighten-4 right" href="#!">Account</a>
      <a class="grey-text text-lighten-4 right padding-footer" href="#!">Enrollment</a>
      <a class="grey-text text-lighten-4 right padding-footer" href="#!">Courses</a>
      </div>
    </div>
  </footer>

app/views/layouts/_navigation.html.erb
<header>
  <ul id="dropdown1" class="dropdown-content">
    <li><%= session_link %></li>
    <li class="divider"></li>
    <% if logged_in? %>
    <li><%= link_to 'Profile', student_path(current_user) %></li>
    <% end %>
    <li class="divider"></li>
    <% if !logged_in? %>
    <li><%= link_to 'Sign up', signup_path %></li>
    <% end %>
  </ul>
  <ul id="dropdown2" class="dropdown-content">
    <li><%= session_link %></li>
    <li class="divider"></li>
    <% if logged_in? %>
    <li><%= link_to 'Profile', student_path(current_user) %></li>
    <% end %>
    <li class="divider"></li>
    <% if !logged_in? %>
    <li><%= link_to 'Sign up', signup_path %></li>
    <% end %>
  </ul>
  <nav>
  <div class="container">
    <div class="nav-wrapper">
      <%= link_to "Tech University", root_path, class: "brand-logo" %>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <% if logged_in? && current_user.admin? %>
        <li><%= link_to 'New Course', new_course_path %> </li>
        <% end %>
        <li><%= link_to 'Courses', root_path %> </li>
        <% if logged_in? %>
        <li><%= link_to "Enrollment", students_path %></li>
        <% end %>
        <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Account<i class="material-icons right">arrow_drop_down</i></a></li>
      </ul>
    </div>
    </div>
  </nav>
    <ul class="sidenav" id="mobile-demo">
    <% if logged_in? && current_user.admin? %>
     <li><%= link_to 'New Course', new_course_path %> </li>
    <% end %>
    <li><%= link_to 'Courses', root_path %> </li>
    <% if logged_in? %>
     <li><%= link_to "Enrollment", students_path %> </li>
    <% end %>
    <li><a class="dropdown-trigger" href="#!" data-target="dropdown2">Account<i class="material-icons right">arrow_drop_down</i></a></li>
  </ul>
  <% flash.each do |key, message| %>
  <div class="container">
    <div class="row sign-up-form">
        <div class="col m12">
            <div class="card-panel red lighten-2" id= "fade-out-target">
                <span class="white-text">
                   <%= message %> 
                  </span>
                </div>
            </div>
        </div>
    </div>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Uniapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/logins/new.html.erb
<div class="container">
    <div class="row sign-up-form">
        <div class="col m12">
            <div class="card-panel">
              <div class="card-title">
               <h3 class="teal-text center">Log in</h3>  
              </div>
               <div class="row">
                <%= form_for(:logins, html: { class: 'col m12' }) do | f | %>
                    <div class="row">
                     <div class="input-field col m12">
                        <%= f.email_field :email, placeholder: 'Enter your email address', autofocus: true %>
                        <%= f.label :email, class: "active" %>
                     </div>
                 </div>
                 <div class="row">
                     <div class="input-field col m12">
                        <%= f.password_field :password, placeholder: 'Enter your password', autofocus: true %>
                        <%= f.label :password, class: "active" %>
                     </div>
                 </div>
                  <div class="row">
                    <div class="input-field col m12">               
                     <%= f.button '<i class="material-icons right">send</i>log in'.html_safe, 
                                     class: "btn waves-effect waves-light right white-text" %>
                   </div>  
                 </div>
                <% end %>
            </div>  
          </div>
        </div>
    </div>
</div>

app/views/pages/about.html.erb
<h1>This is university about page</h1>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="container">
    <div class="row sign-up-form">
        <div class="col m12">
            <div class="card-panel red lighten-2">
                <span class="white-text">
                    <h6><%= pluralize(obj.errors.count, "error") %>
                      Prohibited your profile from being created</h6>
                      <ul>
                      <% @student.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                     <% end %>
                     </ul>
                    </span>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/students/_form.html.erb
<%= render 'shared/errors', obj: @student %>
<div class="container">
    <div class="row sign-up-form">
        <div class="col m12">
            <div class="card-panel">
              <div class="card-title">
               <h3 class="teal-text center"><%= @student.new_record? ? 'Sign Up!' : 'Edit your profile!' %></h3>  
              </div>
               <div class="row">
                <%= form_for(@student, html: { class: 'col m12' }) do | f | %>
                 <div class="row">
                     <div class="input-field col m12">
                        <%= f.text_field :name, placeholder: 'Enter your full name', autofocus: true %>
                        <%= f.label :name, class: "active" %>
                     </div>
                 </div>
                    <div class="row">
                     <div class="input-field col m12">
                        <%= f.email_field :email, placeholder: 'Enter your email address', autofocus: true %>
                        <%= f.label :email, class: "active" %>
                     </div>
                 </div>
                 <div class="row">
                     <div class="input-field col m12">
                        <%= f.password_field :password, placeholder: 'Choose password', autofocus: true %>
                        <%= f.label :password, class: "active" %>
                     </div>
                 </div>
                  <div class="row">
                     <div class="input-field col m12">
                        <%= f.password_field :confirm_password, placeholder: 'Confirm password', autofocus: true %>
                        <%= f.label :confirm_password, class: "active" %>
                     </div>
                 </div>
                  <div class="row">
                    <div class="input-field col m12">               
                     <%= f.button(@student.new_record? ? '<i class="material-icons right">send</i>submit'.html_safe : 
                                     '<i class="material-icons right">send</i>submit changes'.html_safe, 
                                     class: "btn waves-effect waves-light right white-text") %>
                   </div>  
                 </div>
                <% end %>
            </div>  
          </div>
        </div>
    </div>
</div>

app/views/students/edit.html.erb
<div class="row">
    <div class="col s12">
        <%= render 'form' %>
    </div>
</div>

app/views/students/index.html.erb
<div class="row">
  <div class="col m12">
   <div class="course_heading">
        <h1>Students Directory</h1>
   </div>
  </div>
 </div>
<div class="row">
    <% @students.each do |student| %>
    <div class="col s12 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Name: <%= student.name %></span>
          <p>Email: <%= student.email %> </p>
          <p><strong>Course enrollment:</strong> 
         <% if student.courses.empty? %>
            None
          <% else %>
            <%=student.courses.count %>
          <% end %>
         </p>
        </div>
        <div class="card-action">
          <%= link_to "View profile", student_path(student) %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
               

app/views/students/new.html.erb
<div class="row">
    <div class="col s12">
        <%= render 'form' %>
    </div>
</div>

app/views/students/show.html.erb
<div class="row sign-up-form">
    <div class="col s12 m6 l6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Name: <%= @student.name %></span>
          <p>Email: <%= @student.email %> </p>
          <p><strong>Course enrollment :</strong>
          <% if @student.courses.empty? %>
            None
          <% else %>
         <ul>
          <% @student.courses.each do |course| %>
           <li><%= course.name %></li>
          <% end %>
         </ul>
          <% end %>
          </p>
        </div>
      </div>
      <% if current_user == @student %>
      <%= link_to '<i class="material-icons right">create</i>Edit your profile'.html_safe, 
       edit_student_path(@student), class: "waves-effect waves-light btn" %>
       <% end %>
    </div>
 </div>